#include "generate_test_ship.hpp"
#include "xdyn/external_file_formats/stl_reader.hpp"
#include "base91x/base91.hpp"

VectorOfVectorOfPoints test_ship() // Generated by convert_stl_files_to_code
{
    #include "test_ship_data.hpp"
    return read_binary_stl(base<91>::decode(s));
}
