FROM ubuntu:22.04
RUN apt-get update -yq \
 && apt-get install --yes --no-install-recommends \
    python3 \
    python3-pip \ # Needed to install xdyn's wheel
    python3-numpy \ # Numpy is a dependency for xdyn's Python wrapper
 && python3 --version
ADD xdyn*cp310*-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / xdyn \
 && python3 -c 'import xdyn; print(dir(xdyn)); print(xdyn.__version__)'
