ARG DOCKER_BASE_IMAGE=debian:bullseye-slim
FROM ${DOCKER_BASE_IMAGE}
RUN apt-get update -yq \
 && apt-get install --yes --no-install-recommends \
    libgfortran5 \
    libquadmath0 \
    python3 \
    python3-pip \
    wait-for-it \
 && python3 --version \
 && python3 -m pip install -U pip \
 && python3 -m pip install \
    grpcio \
    protobuf \
    numpy \
 && apt-get autoclean \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /tmp/* /var/tmp/* \
 && rm -rf /var/lib/apt/lists

ADD xdyngrpc*.whl /
RUN python3 -m pip install --find-links / xdyngrpc \
 && python3 -c 'import xdyngrpc; print(dir(xdyngrpc)); print(xdyngrpc.__version__)'
ADD xdyn.deb /
RUN dpkg -i /xdyn.deb
ARG PYTHON_MAJOR_VERSION=3
ARG PYTHON_MINOR_VERSION=9
ADD xdyn*cp${PYTHON_MAJOR_VERSION}${PYTHON_MINOR_VERSION}*-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / xdyn \
 && python3 -c 'import xdyn; print(dir(xdyn)); print(xdyn.__version__)'
ENV PYTHONPATH /usr/python
ENTRYPOINT ["python3"]
