FROM alpine
RUN apk --no-cache add \
    terminus-font ttf-inconsolata ttf-dejavu font-noto font-noto-cjk ttf-font-awesome font-noto-extra \
    inkscape
RUN mkdir -p /.config/inkscape && chmod a+x /.config/inkscape
