.PHONY: all clean

all:
	@make -C force
	@make -C waves
	@make -C wave+force
	@make -C cosim
	@make -C model_exchange
	@make -C controller

clean:
	@make -C force $@
	@make -C waves $@
	@make -C cosim $@
	@make -C model_exchange $@
	@make -C controller $@
