FROM sirehna/base-image-debian11-gcc10:2021-08-17
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    wget \
    libbz2-dev \
 && wget https://www.python.org/ftp/python/3.10.1/Python-3.10.1.tgz \
 && tar -xf Python-3.10.1.tgz \
 && cd Python-3.10.1 \
 && ./configure --enable-optimizations \
 && make altinstall \
 && cd .. \
 && rm -rf Python-3.10.1 \
 && rm -f Python-3.10.1.tgz \
 && python3.10 --version \
 && which python3.10 \
 && ln -s /usr/local/bin/python3.10 /usr/local/bin/python3 \
 && which python3
RUN python3.10 -m pip install -U pip \
 && python3.10 -m pip install \
    wheel \
    pybind11[global]==2.8.1
