FROM debian:bullseye-slim
# One requires:
# - python3:
# - python3-numpy: Numpy is a dependency for xdyn
# - python3-pip: Needed to install the wheel
# - python3-nose: Needed to run unit test
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    python3 \
    python3-numpy \
    python3-nose \
    python3-pip
ADD xdyn-*-cp39-cp39-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / xdyn \
 && python3 -c 'import xdyn; print(dir(xdyn))'
