FROM sirehna/base-image-debian10-gcc8-xdyn:2021-04-16
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    cmake \
    python3 \
    python3-dev \
    python3-setuptools \
    python3-wheel \
    pybind11-dev \
    python3-pybind11
