FROM sirehna/base-image-debian11-gcc10:2021-08-17
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    python3 \
    python3-numpy \
    python3-pip
ADD pyxdyn-0.0.1-cp39-cp39-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / pyxdyn \
 && python3 -c 'import pyxdyn; print(dir(pyxdyn))'
