ARG DOCKER_BASE_IMAGE=debian:bullseye-slim
FROM ${DOCKER_BASE_IMAGE}
RUN apt-get update -yq \
 && apt-get install --yes --no-install-recommends \
    libgfortran5 \
    libquadmath0 \
    python3 \
    python3-pip \
    wait-for-it \
 && python3 --version \
 && python3 -m pip install -U pip \
 && python3 -m pip install \
    grpcio-tools \
    grpcio \
    numpy \
 && apt-get autoclean \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /tmp/* /var/tmp/* \
 && rm -rf /var/lib/apt/lists

ADD xdyn.deb /
RUN dpkg -i /xdyn.deb \
 && ls /usr/proto \
 && mkdir -p /usr/python3 \
 && chmod a+rwx /usr/python3 \
 && cd /usr/proto \
 && python3 -m grpc_tools.protoc -I . --python_out=/usr/python3 --grpc_python_out=/usr/python3 \
    controller.proto \
    cosimulation.proto \
    force.proto \
    model_exchange.proto \
    wave_grpc.proto \
    wave_types.proto \
 && PYTHONPATH=/usr/python3 python3 -c'import controller_pb2, cosimulation_pb2, force_pb2, model_exchange_pb2, wave_grpc_pb2, wave_types_pb2' \
 && PYTHONPATH=/usr/python3 python3 -c'import controller_pb2_grpc, cosimulation_pb2_grpc, force_pb2_grpc, model_exchange_pb2_grpc, wave_grpc_pb2_grpc, wave_types_pb2_grpc'
ARG PYTHON_MAJOR_VERSION=3
ARG PYTHON_MINOR_VERSION=9
ADD xdyn*cp${PYTHON_MAJOR_VERSION}${PYTHON_MINOR_VERSION}*-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / xdyn \
 && python3 -c 'import xdyn; print(dir(xdyn)); print(xdyn.__version__)'
ENV PYTHONPATH /usr/python
ENTRYPOINT ["python3"]
