FROM python:3.10.1-slim-bullseye
# One requires:
# - python3:
# - python3-numpy: Numpy is a dependency for xdyn
# - python3-pip: Needed to install the wheel
RUN python3 -m pip install -U pip \
 && python3 -m pip install \
    numpy
ADD xdyn-*-cp310-cp310-linux_x86_64.whl /
RUN python3 -m pip install --no-index --find-links / xdyn \
 && python3 -c 'import xdyn; print(dir(xdyn))'
