FROM sirehna/base-image-debian11-gcc10:2021-08-17
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    cmake \
    python3 \
    python3-dev \
    python3-setuptools \
    python3-wheel \
    pybind11-dev \
    python3-pybind11
