FROM sirehna/base-image-debian11-gcc10:2021-08-17
RUN apt-get update -yq || true \
 && apt-get install --yes --no-install-recommends \
    cmake \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel
RUN python3 -m pip install -U pip \
 && python3 -m pip install \
    pybind11[global]==2.8.1
