IF(MINGW)
    SET(PROTOBUF_LIBPROTOBUF /opt/ProtoBuf/lib/libprotobuf.a)
    SET(PROTOBUF_PROTOC wine /opt/ProtoBuf/bin/protoc.exe-3.7.0.0)
    SET(PROTOC_PREFIX "Z:")
    SET(PROTOBUF_INCLUDE_DIR /opt/ProtoBuf/include)
    SET(PROTOBUF_MIN_PROTOC_VERSION 3007000)
ELSE()
    IF(CMAKE_COMPILER_IS_GNUCC AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 10)
        MESSAGE(STATUS "Using protobuf library from distribution without -fPIC flag")
        SET(PROTOBUF_LIBPROTOBUF /usr/lib/x86_64-linux-gnu/libprotobuf.a)
    ELSE()
        MESSAGE(STATUS "Using protobuf library compiled with -fPIC option to create shared library")
        SET(PROTOBUF_LIBPROTOBUF /opt/grpc/lib/libprotobuf.a)
    ENDIF()
    SET(PROTOBUF_PROTOC protoc)
    SET(PROTOC_PREFIX "")
    SET(PROTOBUF_INCLUDE_DIR /usr/include)
ENDIF()
