issue_202: issue_202.csv issue_202.py
	@echo "Checking forces & torques are outputted in the right frame (issue #202)"
	@${DOCKER_RUN} --entrypoint python python:3.10-slim issue_202.py
	@echo "✓ Output is correct!"

issue_202.csv: issue_202.yml
	@echo "Running simulation for issue 202..."
	${DOCKER_RUN} xdyn:latest issue_202.yml --dt 1 --tend 2
	@echo "Done!"
